# Generated by Django 4.2 on 2024-09-12 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('news', 'News'), ('free', '자유게시판')], default='news', max_length=10),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
