# Generated by Django 4.2 on 2024-09-12 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_remove_article_categories_remove_article_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('News', 'News'), ('자유게시판', '자유게시판')], default='news', max_length=10),
        ),
    ]
